sonar.projectKey=AloysHF_WQXEmu
sonar.projectName=WQXEmu
sonar.organization=aloyshf-github

sonar.sources=crates
sonar.exclusions=**/target/**
sonar.sourceEncoding=UTF-8

sonar.rust.cobertura.reportPaths=coverage/cobertura.xml
