[package]
name = "wqxemu-core"
version.workspace = true
edition.workspace = true
description = "Platform-independent Wenquxing NC1020 hardware emulation core"
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
log.workspace = true
serde.workspace = true
bincode.workspace = true

[dev-dependencies]
cargo-husky = { version = "1", default-features = false, features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"] }
