// Model-specific keyboard layouts.
//
// Every Wenquxing model exposes an 8x8 keypad matrix, but the physical
// key arrangement (and therefore which PC key maps to which matrix
// position) differs per model. This module is the single source of
// truth for the frontends: it describes the on-screen keys (label, PC
// key hint) for each supported model so the desktop frontend can draw a
// virtual keypad and accept mouse clicks.

use crate::machine::MachineModel;

/// A single on-screen key.
///
/// `drow`/`dcol` are the physical display position (6 rows x 10 cols,
/// matching the real Wenquxing keypad), while `row`/`col` are the keypad
/// matrix coordinates used for input.
#[derive(Clone, Copy, Debug)]
pub struct KeyDef {
    /// Physical display row (0-5).
    pub drow: u8,
    /// Physical display column (0-9).
    pub dcol: u8,
    /// Keypad matrix row (0-7).
    pub row: u8,
    /// Keypad matrix column (0-7).
    pub col: u8,
    /// Key-face label shown on the virtual keypad (ASCII).
    pub label: &'static str,
    /// PC key hint (e.g. "F5", "A", "UP"); empty when unmapped.
    pub hint: &'static str,
}

/// Key ID for a matrix position in the machine encoding.
///
/// Most models encode `key_id = row << 3 | col`, but the NC1020 family
/// (following the NC1020 reference implementation) encodes the opposite
/// way: `row = key_id % 8`, `col = key_id / 8`.
pub fn key_id_for(model: MachineModel, row: u8, col: u8) -> u8 {
    match model {
        MachineModel::Nc1020 => (col << 3) | row,
        _ => (row << 3) | col,
    }
}

/// NC2000 keypad: standard 6x10 keypad with hotkeys in matrix column 1.
const LAYOUT_NC2000: &[KeyDef] = &[
    // Top row: hotkeys (英汉 名片 计算 行程 资料 时间 网络).
    KeyDef {
        drow: 0,
        dcol: 0,
        row: 3,
        col: 1,
        label: "DICT",
        hint: "F5",
    },
    KeyDef {
        drow: 0,
        dcol: 1,
        row: 4,
        col: 1,
        label: "CARD",
        hint: "F6",
    },
    KeyDef {
        drow: 0,
        dcol: 2,
        row: 5,
        col: 1,
        label: "CALC",
        hint: "F7",
    },
    KeyDef {
        drow: 0,
        dcol: 3,
        row: 2,
        col: 1,
        label: "MEMO",
        hint: "F8",
    },
    KeyDef {
        drow: 0,
        dcol: 4,
        row: 1,
        col: 1,
        label: "DATA",
        hint: "F9",
    },
    KeyDef {
        drow: 0,
        dcol: 5,
        row: 0,
        col: 1,
        label: "TIME",
        hint: "F10",
    },
    KeyDef {
        drow: 0,
        dcol: 6,
        row: 6,
        col: 1,
        label: "NET",
        hint: "F11",
    },
    // Function keys + power.
    KeyDef {
        drow: 1,
        dcol: 2,
        row: 0,
        col: 2,
        label: "F1",
        hint: "F1",
    },
    KeyDef {
        drow: 1,
        dcol: 3,
        row: 1,
        col: 2,
        label: "F2",
        hint: "F2",
    },
    KeyDef {
        drow: 1,
        dcol: 4,
        row: 2,
        col: 2,
        label: "F3",
        hint: "F3",
    },
    KeyDef {
        drow: 1,
        dcol: 5,
        row: 3,
        col: 2,
        label: "F4",
        hint: "F4",
    },
    KeyDef {
        drow: 1,
        dcol: 8,
        row: 0,
        col: 0,
        label: "ON",
        hint: "F12",
    },
    // QWERTY rows (matrix columns 4,5,6 and 3).
    KeyDef {
        drow: 2,
        dcol: 0,
        row: 0,
        col: 4,
        label: "Q",
        hint: "Q",
    },
    KeyDef {
        drow: 2,
        dcol: 1,
        row: 1,
        col: 4,
        label: "W",
        hint: "W",
    },
    KeyDef {
        drow: 2,
        dcol: 2,
        row: 2,
        col: 4,
        label: "E",
        hint: "E",
    },
    KeyDef {
        drow: 2,
        dcol: 3,
        row: 3,
        col: 4,
        label: "R",
        hint: "R",
    },
    KeyDef {
        drow: 2,
        dcol: 4,
        row: 4,
        col: 4,
        label: "T",
        hint: "T/7",
    },
    KeyDef {
        drow: 2,
        dcol: 5,
        row: 5,
        col: 4,
        label: "Y",
        hint: "Y/8",
    },
    KeyDef {
        drow: 2,
        dcol: 6,
        row: 6,
        col: 4,
        label: "U",
        hint: "U/9",
    },
    KeyDef {
        drow: 2,
        dcol: 7,
        row: 7,
        col: 4,
        label: "I",
        hint: "I",
    },
    KeyDef {
        drow: 2,
        dcol: 8,
        row: 0,
        col: 3,
        label: "O",
        hint: "O",
    },
    KeyDef {
        drow: 2,
        dcol: 9,
        row: 4,
        col: 3,
        label: "P",
        hint: "P",
    },
    KeyDef {
        drow: 3,
        dcol: 0,
        row: 0,
        col: 5,
        label: "A",
        hint: "A",
    },
    KeyDef {
        drow: 3,
        dcol: 1,
        row: 1,
        col: 5,
        label: "S",
        hint: "S",
    },
    KeyDef {
        drow: 3,
        dcol: 2,
        row: 2,
        col: 5,
        label: "D",
        hint: "D",
    },
    KeyDef {
        drow: 3,
        dcol: 3,
        row: 3,
        col: 5,
        label: "F",
        hint: "F",
    },
    KeyDef {
        drow: 3,
        dcol: 4,
        row: 4,
        col: 5,
        label: "G",
        hint: "G/4",
    },
    KeyDef {
        drow: 3,
        dcol: 5,
        row: 5,
        col: 5,
        label: "H",
        hint: "H/5",
    },
    KeyDef {
        drow: 3,
        dcol: 6,
        row: 6,
        col: 5,
        label: "J",
        hint: "J/6",
    },
    KeyDef {
        drow: 3,
        dcol: 7,
        row: 7,
        col: 5,
        label: "K",
        hint: "K",
    },
    KeyDef {
        drow: 3,
        dcol: 8,
        row: 1,
        col: 3,
        label: "L",
        hint: "L",
    },
    KeyDef {
        drow: 3,
        dcol: 9,
        row: 5,
        col: 3,
        label: "ENT",
        hint: "ENT",
    },
    KeyDef {
        drow: 4,
        dcol: 0,
        row: 0,
        col: 6,
        label: "Z",
        hint: "Z",
    },
    KeyDef {
        drow: 4,
        dcol: 1,
        row: 1,
        col: 6,
        label: "X",
        hint: "X",
    },
    KeyDef {
        drow: 4,
        dcol: 2,
        row: 2,
        col: 6,
        label: "C",
        hint: "C",
    },
    KeyDef {
        drow: 4,
        dcol: 3,
        row: 3,
        col: 6,
        label: "V",
        hint: "V",
    },
    KeyDef {
        drow: 4,
        dcol: 4,
        row: 4,
        col: 6,
        label: "B",
        hint: "B/1",
    },
    KeyDef {
        drow: 4,
        dcol: 5,
        row: 5,
        col: 6,
        label: "N",
        hint: "N/2",
    },
    KeyDef {
        drow: 4,
        dcol: 6,
        row: 6,
        col: 6,
        label: "M",
        hint: "M/3",
    },
    KeyDef {
        drow: 4,
        dcol: 7,
        row: 7,
        col: 6,
        label: "PGUP",
        hint: "PGUP",
    },
    KeyDef {
        drow: 4,
        dcol: 8,
        row: 2,
        col: 3,
        label: "UP",
        hint: "UP",
    },
    KeyDef {
        drow: 4,
        dcol: 9,
        row: 6,
        col: 3,
        label: "PGDN",
        hint: "PGDN",
    },
    // Bottom row.
    KeyDef {
        drow: 5,
        dcol: 0,
        row: 0,
        col: 7,
        label: "HELP",
        hint: "",
    },
    KeyDef {
        drow: 5,
        dcol: 1,
        row: 1,
        col: 7,
        label: "SHIFT",
        hint: "",
    },
    KeyDef {
        drow: 5,
        dcol: 2,
        row: 2,
        col: 7,
        label: "IME",
        hint: "",
    },
    KeyDef {
        drow: 5,
        dcol: 3,
        row: 3,
        col: 7,
        label: "ESC",
        hint: "ESC",
    },
    KeyDef {
        drow: 5,
        dcol: 4,
        row: 4,
        col: 7,
        label: "0",
        hint: "0",
    },
    KeyDef {
        drow: 5,
        dcol: 5,
        row: 5,
        col: 7,
        label: ".",
        hint: ".",
    },
    KeyDef {
        drow: 5,
        dcol: 6,
        row: 6,
        col: 7,
        label: "SPC",
        hint: "SPC",
    },
    KeyDef {
        drow: 5,
        dcol: 7,
        row: 7,
        col: 7,
        label: "LT",
        hint: "LT",
    },
    KeyDef {
        drow: 5,
        dcol: 8,
        row: 3,
        col: 3,
        label: "DN",
        hint: "DN",
    },
    KeyDef {
        drow: 5,
        dcol: 9,
        row: 7,
        col: 3,
        label: "RT",
        hint: "RT",
    },
];

/// NC3000 keypad: standard 6x10 keypad with hotkeys in matrix column 0.
const LAYOUT_NC3000: &[KeyDef] = &[
    // Top row: 游戏 计算 时间 英汉 词库 学习.
    KeyDef {
        drow: 0,
        dcol: 0,
        row: 1,
        col: 0,
        label: "GAME",
        hint: "F5",
    },
    KeyDef {
        drow: 0,
        dcol: 1,
        row: 2,
        col: 0,
        label: "CALC",
        hint: "F6",
    },
    KeyDef {
        drow: 0,
        dcol: 2,
        row: 3,
        col: 0,
        label: "TIME",
        hint: "F7",
    },
    KeyDef {
        drow: 0,
        dcol: 3,
        row: 5,
        col: 0,
        label: "DICT",
        hint: "F9",
    },
    KeyDef {
        drow: 0,
        dcol: 4,
        row: 6,
        col: 0,
        label: "LEX",
        hint: "F10",
    },
    KeyDef {
        drow: 0,
        dcol: 5,
        row: 7,
        col: 0,
        label: "STUDY",
        hint: "F11",
    },
    // Function keys + power (网络/电源).
    KeyDef {
        drow: 1,
        dcol: 2,
        row: 0,
        col: 2,
        label: "F1",
        hint: "F1",
    },
    KeyDef {
        drow: 1,
        dcol: 3,
        row: 1,
        col: 2,
        label: "F2",
        hint: "F2",
    },
    KeyDef {
        drow: 1,
        dcol: 4,
        row: 2,
        col: 2,
        label: "F3",
        hint: "F3",
    },
    KeyDef {
        drow: 1,
        dcol: 5,
        row: 3,
        col: 2,
        label: "F4",
        hint: "F4",
    },
    KeyDef {
        drow: 1,
        dcol: 8,
        row: 0,
        col: 0,
        label: "PWR",
        hint: "F12",
    },
    // QWERTY rows (matrix columns 4,5,6 and 3).
    KeyDef {
        drow: 2,
        dcol: 0,
        row: 0,
        col: 4,
        label: "Q",
        hint: "Q",
    },
    KeyDef {
        drow: 2,
        dcol: 1,
        row: 1,
        col: 4,
        label: "W",
        hint: "W",
    },
    KeyDef {
        drow: 2,
        dcol: 2,
        row: 2,
        col: 4,
        label: "E",
        hint: "E",
    },
    KeyDef {
        drow: 2,
        dcol: 3,
        row: 3,
        col: 4,
        label: "R",
        hint: "R",
    },
    KeyDef {
        drow: 2,
        dcol: 4,
        row: 4,
        col: 4,
        label: "T",
        hint: "T/7",
    },
    KeyDef {
        drow: 2,
        dcol: 5,
        row: 5,
        col: 4,
        label: "Y",
        hint: "Y/8",
    },
    KeyDef {
        drow: 2,
        dcol: 6,
        row: 6,
        col: 4,
        label: "U",
        hint: "U/9",
    },
    KeyDef {
        drow: 2,
        dcol: 7,
        row: 7,
        col: 4,
        label: "I",
        hint: "I",
    },
    KeyDef {
        drow: 2,
        dcol: 8,
        row: 0,
        col: 3,
        label: "O",
        hint: "O",
    },
    KeyDef {
        drow: 2,
        dcol: 9,
        row: 4,
        col: 3,
        label: "P",
        hint: "P",
    },
    KeyDef {
        drow: 3,
        dcol: 0,
        row: 0,
        col: 5,
        label: "A",
        hint: "A",
    },
    KeyDef {
        drow: 3,
        dcol: 1,
        row: 1,
        col: 5,
        label: "S",
        hint: "S",
    },
    KeyDef {
        drow: 3,
        dcol: 2,
        row: 2,
        col: 5,
        label: "D",
        hint: "D",
    },
    KeyDef {
        drow: 3,
        dcol: 3,
        row: 3,
        col: 5,
        label: "F",
        hint: "F",
    },
    KeyDef {
        drow: 3,
        dcol: 4,
        row: 4,
        col: 5,
        label: "G",
        hint: "G/4",
    },
    KeyDef {
        drow: 3,
        dcol: 5,
        row: 5,
        col: 5,
        label: "H",
        hint: "H/5",
    },
    KeyDef {
        drow: 3,
        dcol: 6,
        row: 6,
        col: 5,
        label: "J",
        hint: "J/6",
    },
    KeyDef {
        drow: 3,
        dcol: 7,
        row: 7,
        col: 5,
        label: "K",
        hint: "K",
    },
    KeyDef {
        drow: 3,
        dcol: 8,
        row: 1,
        col: 3,
        label: "L",
        hint: "L",
    },
    KeyDef {
        drow: 3,
        dcol: 9,
        row: 5,
        col: 3,
        label: "ENT",
        hint: "ENT",
    },
    KeyDef {
        drow: 4,
        dcol: 0,
        row: 0,
        col: 6,
        label: "Z",
        hint: "Z",
    },
    KeyDef {
        drow: 4,
        dcol: 1,
        row: 1,
        col: 6,
        label: "X",
        hint: "X",
    },
    KeyDef {
        drow: 4,
        dcol: 2,
        row: 2,
        col: 6,
        label: "C",
        hint: "C",
    },
    KeyDef {
        drow: 4,
        dcol: 3,
        row: 3,
        col: 6,
        label: "V",
        hint: "V",
    },
    KeyDef {
        drow: 4,
        dcol: 4,
        row: 4,
        col: 6,
        label: "B",
        hint: "B/1",
    },
    KeyDef {
        drow: 4,
        dcol: 5,
        row: 5,
        col: 6,
        label: "N",
        hint: "N/2",
    },
    KeyDef {
        drow: 4,
        dcol: 6,
        row: 6,
        col: 6,
        label: "M",
        hint: "M/3",
    },
    KeyDef {
        drow: 4,
        dcol: 7,
        row: 7,
        col: 6,
        label: "PGUP",
        hint: "PGUP",
    },
    KeyDef {
        drow: 4,
        dcol: 8,
        row: 2,
        col: 3,
        label: "UP",
        hint: "UP",
    },
    KeyDef {
        drow: 4,
        dcol: 9,
        row: 6,
        col: 3,
        label: "PGDN",
        hint: "PGDN",
    },
    // Bottom row.
    KeyDef {
        drow: 5,
        dcol: 0,
        row: 0,
        col: 7,
        label: "HELP",
        hint: "",
    },
    KeyDef {
        drow: 5,
        dcol: 1,
        row: 1,
        col: 7,
        label: "SHIFT",
        hint: "",
    },
    KeyDef {
        drow: 5,
        dcol: 2,
        row: 2,
        col: 7,
        label: "IME",
        hint: "",
    },
    KeyDef {
        drow: 5,
        dcol: 3,
        row: 3,
        col: 7,
        label: "ESC",
        hint: "ESC",
    },
    KeyDef {
        drow: 5,
        dcol: 4,
        row: 4,
        col: 7,
        label: "0",
        hint: "0",
    },
    KeyDef {
        drow: 5,
        dcol: 5,
        row: 5,
        col: 7,
        label: ".",
        hint: ".",
    },
    KeyDef {
        drow: 5,
        dcol: 6,
        row: 6,
        col: 7,
        label: "SPC",
        hint: "SPC",
    },
    KeyDef {
        drow: 5,
        dcol: 7,
        row: 7,
        col: 7,
        label: "LT",
        hint: "LT",
    },
    KeyDef {
        drow: 5,
        dcol: 8,
        row: 3,
        col: 3,
        label: "DN",
        hint: "DN",
    },
    KeyDef {
        drow: 5,
        dcol: 9,
        row: 7,
        col: 3,
        label: "RT",
        hint: "RT",
    },
];

/// PC1000 / CC800 keypad (same matrix, from the PC1000 reference keymap).
const LAYOUT_PC1000: &[KeyDef] = &[
    // Top row: hotkeys.
    KeyDef {
        drow: 0,
        dcol: 0,
        row: 1,
        col: 0,
        label: "DICT",
        hint: "F5",
    },
    KeyDef {
        drow: 0,
        dcol: 1,
        row: 1,
        col: 1,
        label: "CARD",
        hint: "F6",
    },
    KeyDef {
        drow: 0,
        dcol: 2,
        row: 1,
        col: 2,
        label: "CALC",
        hint: "F7",
    },
    KeyDef {
        drow: 0,
        dcol: 3,
        row: 1,
        col: 3,
        label: "MEMO",
        hint: "F8",
    },
    KeyDef {
        drow: 0,
        dcol: 4,
        row: 1,
        col: 4,
        label: "DATA",
        hint: "F9",
    },
    KeyDef {
        drow: 0,
        dcol: 5,
        row: 1,
        col: 5,
        label: "TIME",
        hint: "F10",
    },
    KeyDef {
        drow: 0,
        dcol: 6,
        row: 1,
        col: 6,
        label: "NET",
        hint: "F11",
    },
    // Function keys + power.
    KeyDef {
        drow: 1,
        dcol: 2,
        row: 7,
        col: 2,
        label: "F1",
        hint: "F1",
    },
    KeyDef {
        drow: 1,
        dcol: 3,
        row: 7,
        col: 3,
        label: "F2",
        hint: "F2",
    },
    KeyDef {
        drow: 1,
        dcol: 4,
        row: 7,
        col: 4,
        label: "F3",
        hint: "F3",
    },
    KeyDef {
        drow: 1,
        dcol: 5,
        row: 7,
        col: 5,
        label: "F4",
        hint: "F4",
    },
    KeyDef {
        drow: 1,
        dcol: 8,
        row: 0,
        col: 0,
        label: "ON",
        hint: "F12",
    },
    // QWERTY rows.
    KeyDef {
        drow: 2,
        dcol: 0,
        row: 5,
        col: 0,
        label: "Q",
        hint: "Q",
    },
    KeyDef {
        drow: 2,
        dcol: 1,
        row: 5,
        col: 1,
        label: "W",
        hint: "W",
    },
    KeyDef {
        drow: 2,
        dcol: 2,
        row: 5,
        col: 2,
        label: "E",
        hint: "E",
    },
    KeyDef {
        drow: 2,
        dcol: 3,
        row: 5,
        col: 3,
        label: "R",
        hint: "R",
    },
    KeyDef {
        drow: 2,
        dcol: 4,
        row: 5,
        col: 4,
        label: "T",
        hint: "T/7",
    },
    KeyDef {
        drow: 2,
        dcol: 5,
        row: 5,
        col: 5,
        label: "Y",
        hint: "Y/8",
    },
    KeyDef {
        drow: 2,
        dcol: 6,
        row: 5,
        col: 6,
        label: "U",
        hint: "U/9",
    },
    KeyDef {
        drow: 2,
        dcol: 7,
        row: 5,
        col: 7,
        label: "I",
        hint: "I",
    },
    KeyDef {
        drow: 2,
        dcol: 8,
        row: 6,
        col: 0,
        label: "O",
        hint: "O",
    },
    KeyDef {
        drow: 2,
        dcol: 9,
        row: 6,
        col: 4,
        label: "P",
        hint: "P",
    },
    KeyDef {
        drow: 3,
        dcol: 0,
        row: 4,
        col: 0,
        label: "A",
        hint: "A",
    },
    KeyDef {
        drow: 3,
        dcol: 1,
        row: 4,
        col: 1,
        label: "S",
        hint: "S",
    },
    KeyDef {
        drow: 3,
        dcol: 2,
        row: 4,
        col: 2,
        label: "D",
        hint: "D",
    },
    KeyDef {
        drow: 3,
        dcol: 3,
        row: 4,
        col: 3,
        label: "F",
        hint: "F",
    },
    KeyDef {
        drow: 3,
        dcol: 4,
        row: 4,
        col: 4,
        label: "G",
        hint: "G/4",
    },
    KeyDef {
        drow: 3,
        dcol: 5,
        row: 4,
        col: 5,
        label: "H",
        hint: "H/5",
    },
    KeyDef {
        drow: 3,
        dcol: 6,
        row: 4,
        col: 6,
        label: "J",
        hint: "J/6",
    },
    KeyDef {
        drow: 3,
        dcol: 7,
        row: 4,
        col: 7,
        label: "K",
        hint: "K",
    },
    KeyDef {
        drow: 3,
        dcol: 8,
        row: 6,
        col: 1,
        label: "L",
        hint: "L",
    },
    KeyDef {
        drow: 3,
        dcol: 9,
        row: 6,
        col: 5,
        label: "ENT",
        hint: "ENT",
    },
    KeyDef {
        drow: 4,
        dcol: 0,
        row: 3,
        col: 0,
        label: "Z",
        hint: "Z",
    },
    KeyDef {
        drow: 4,
        dcol: 1,
        row: 3,
        col: 1,
        label: "X",
        hint: "X",
    },
    KeyDef {
        drow: 4,
        dcol: 2,
        row: 3,
        col: 2,
        label: "C",
        hint: "C",
    },
    KeyDef {
        drow: 4,
        dcol: 3,
        row: 3,
        col: 3,
        label: "V",
        hint: "V",
    },
    KeyDef {
        drow: 4,
        dcol: 4,
        row: 3,
        col: 4,
        label: "B",
        hint: "B/1",
    },
    KeyDef {
        drow: 4,
        dcol: 5,
        row: 3,
        col: 5,
        label: "N",
        hint: "N/2",
    },
    KeyDef {
        drow: 4,
        dcol: 6,
        row: 3,
        col: 6,
        label: "M",
        hint: "M/3",
    },
    KeyDef {
        drow: 4,
        dcol: 7,
        row: 3,
        col: 7,
        label: "PGUP",
        hint: "PGUP",
    },
    KeyDef {
        drow: 4,
        dcol: 8,
        row: 6,
        col: 2,
        label: "UP",
        hint: "UP",
    },
    KeyDef {
        drow: 4,
        dcol: 9,
        row: 6,
        col: 6,
        label: "PGDN",
        hint: "PGDN",
    },
    // Bottom row.
    KeyDef {
        drow: 5,
        dcol: 0,
        row: 2,
        col: 0,
        label: "HELP",
        hint: "",
    },
    KeyDef {
        drow: 5,
        dcol: 1,
        row: 2,
        col: 1,
        label: "SHIFT",
        hint: "",
    },
    KeyDef {
        drow: 5,
        dcol: 2,
        row: 2,
        col: 2,
        label: "IME",
        hint: "",
    },
    KeyDef {
        drow: 5,
        dcol: 3,
        row: 2,
        col: 3,
        label: "ESC",
        hint: "ESC",
    },
    KeyDef {
        drow: 5,
        dcol: 4,
        row: 2,
        col: 4,
        label: "0",
        hint: "0",
    },
    KeyDef {
        drow: 5,
        dcol: 5,
        row: 2,
        col: 5,
        label: ".",
        hint: ".",
    },
    KeyDef {
        drow: 5,
        dcol: 6,
        row: 2,
        col: 6,
        label: "SPC",
        hint: "SPC",
    },
    KeyDef {
        drow: 5,
        dcol: 7,
        row: 2,
        col: 7,
        label: "LT",
        hint: "LT",
    },
    KeyDef {
        drow: 5,
        dcol: 8,
        row: 6,
        col: 3,
        label: "DN",
        hint: "DN",
    },
    KeyDef {
        drow: 5,
        dcol: 9,
        row: 6,
        col: 7,
        label: "RT",
        hint: "RT",
    },
];

/// NC1020 keypad (physical layout from the NC1020 web emulator;
/// matrix coordinates decoded from the NC1020 key ID layout).
const LAYOUT_NC1020: &[KeyDef] = &[
    // Top row: F10 (main screen) and F11 (game menu).
    KeyDef {
        drow: 0,
        dcol: 0,
        row: 0,
        col: 1,
        label: "F10",
        hint: "F10",
    },
    KeyDef {
        drow: 0,
        dcol: 1,
        row: 6,
        col: 1,
        label: "F11",
        hint: "F11",
    },
    // Function keys + power.
    KeyDef {
        drow: 1,
        dcol: 2,
        row: 0,
        col: 2,
        label: "F1/1",
        hint: "1",
    },
    KeyDef {
        drow: 1,
        dcol: 3,
        row: 1,
        col: 2,
        label: "F2/2",
        hint: "2",
    },
    KeyDef {
        drow: 1,
        dcol: 4,
        row: 2,
        col: 2,
        label: "F3/3",
        hint: "3",
    },
    KeyDef {
        drow: 1,
        dcol: 5,
        row: 3,
        col: 2,
        label: "F4/4",
        hint: "4",
    },
    KeyDef {
        drow: 1,
        dcol: 8,
        row: 7,
        col: 1,
        label: "ON",
        hint: "DEL",
    },
    // QWERTY rows.
    KeyDef {
        drow: 2,
        dcol: 0,
        row: 1,
        col: 2,
        label: "Q",
        hint: "Q",
    },
    KeyDef {
        drow: 2,
        dcol: 1,
        row: 1,
        col: 6,
        label: "W",
        hint: "W",
    },
    KeyDef {
        drow: 2,
        dcol: 2,
        row: 4,
        col: 2,
        label: "E",
        hint: "E",
    },
    KeyDef {
        drow: 2,
        dcol: 3,
        row: 2,
        col: 2,
        label: "R",
        hint: "R",
    },
    KeyDef {
        drow: 2,
        dcol: 4,
        row: 2,
        col: 4,
        label: "T",
        hint: "T",
    },
    KeyDef {
        drow: 2,
        dcol: 5,
        row: 3,
        col: 6,
        label: "Y",
        hint: "Y",
    },
    KeyDef {
        drow: 2,
        dcol: 6,
        row: 3,
        col: 2,
        label: "U",
        hint: "U",
    },
    KeyDef {
        drow: 2,
        dcol: 7,
        row: 6,
        col: 2,
        label: "I/7",
        hint: "I",
    },
    KeyDef {
        drow: 2,
        dcol: 8,
        row: 0,
        col: 7,
        label: "O",
        hint: "O",
    },
    KeyDef {
        drow: 2,
        dcol: 9,
        row: 0,
        col: 5,
        label: "P",
        hint: "P",
    },
    KeyDef {
        drow: 3,
        dcol: 0,
        row: 0,
        col: 6,
        label: "A",
        hint: "A",
    },
    KeyDef {
        drow: 3,
        dcol: 1,
        row: 1,
        col: 4,
        label: "S",
        hint: "S",
    },
    KeyDef {
        drow: 3,
        dcol: 2,
        row: 3,
        col: 6,
        label: "D",
        hint: "D",
    },
    KeyDef {
        drow: 3,
        dcol: 3,
        row: 4,
        col: 4,
        label: "F",
        hint: "F",
    },
    KeyDef {
        drow: 3,
        dcol: 4,
        row: 5,
        col: 2,
        label: "G/6",
        hint: "G",
    },
    KeyDef {
        drow: 3,
        dcol: 5,
        row: 5,
        col: 4,
        label: "H",
        hint: "H",
    },
    KeyDef {
        drow: 3,
        dcol: 6,
        row: 6,
        col: 4,
        label: "J",
        hint: "J",
    },
    KeyDef {
        drow: 3,
        dcol: 7,
        row: 6,
        col: 6,
        label: "K",
        hint: "K",
    },
    KeyDef {
        drow: 3,
        dcol: 8,
        row: 7,
        col: 2,
        label: "L/8",
        hint: "L",
    },
    KeyDef {
        drow: 3,
        dcol: 9,
        row: 5,
        col: 3,
        label: "ENT",
        hint: "ENT",
    },
    KeyDef {
        drow: 4,
        dcol: 0,
        row: 4,
        col: 6,
        label: "Z",
        hint: "Z",
    },
    KeyDef {
        drow: 4,
        dcol: 1,
        row: 2,
        col: 6,
        label: "X/C",
        hint: "X",
    },
    KeyDef {
        drow: 4,
        dcol: 2,
        row: 3,
        col: 4,
        label: "V",
        hint: "V",
    },
    KeyDef {
        drow: 4,
        dcol: 3,
        row: 1,
        col: 6,
        label: "B/W",
        hint: "B",
    },
    KeyDef {
        drow: 4,
        dcol: 4,
        row: 7,
        col: 6,
        label: "N",
        hint: "N",
    },
    KeyDef {
        drow: 4,
        dcol: 5,
        row: 7,
        col: 4,
        label: "M",
        hint: "M",
    },
    KeyDef {
        drow: 4,
        dcol: 6,
        row: 7,
        col: 6,
        label: "PGUP",
        hint: "PGUP",
    },
    KeyDef {
        drow: 4,
        dcol: 7,
        row: 2,
        col: 3,
        label: "UP",
        hint: "UP",
    },
    KeyDef {
        drow: 4,
        dcol: 8,
        row: 6,
        col: 3,
        label: "PGDN",
        hint: "PGDN",
    },
    KeyDef {
        drow: 4,
        dcol: 9,
        row: 0,
        col: 3,
        label: "9",
        hint: "9",
    },
    // Bottom row.
    KeyDef {
        drow: 5,
        dcol: 3,
        row: 3,
        col: 7,
        label: "ESC",
        hint: "ESC",
    },
    KeyDef {
        drow: 5,
        dcol: 4,
        row: 0,
        col: 4,
        label: "0",
        hint: "0",
    },
    KeyDef {
        drow: 5,
        dcol: 6,
        row: 5,
        col: 6,
        label: "SPC",
        hint: "SPC",
    },
    KeyDef {
        drow: 5,
        dcol: 7,
        row: 7,
        col: 7,
        label: "LT",
        hint: "LT",
    },
    KeyDef {
        drow: 5,
        dcol: 8,
        row: 3,
        col: 3,
        label: "DN",
        hint: "DN",
    },
    KeyDef {
        drow: 5,
        dcol: 9,
        row: 7,
        col: 3,
        label: "RT",
        hint: "RT",
    },
];

/// Keypad layout for a model, used by frontends to draw the virtual
/// keypad and translate mouse clicks.
pub fn layout_for(model: MachineModel) -> &'static [KeyDef] {
    match model {
        MachineModel::Nc1020 => LAYOUT_NC1020,
        MachineModel::Nc2000 => LAYOUT_NC2000,
        MachineModel::Nc3000 => LAYOUT_NC3000,
        MachineModel::Pc1000 | MachineModel::Cc800 => LAYOUT_PC1000,
    }
}
